### PR TITLE
Rewrite for ST4152+

### PR DESCRIPTION
**Pull request by deathaxe**
This PR rewrites Mustache syntax using the schema of [Jinja2](https://github.com/Sublime-Instincts/BetterJinja) package.

It replaces the currently used `push: HTML.sublime-syntax ... with_prototype: ...` construct by extended syntax definitions.

The outcome:

1. Separate Mustache templates for (CSS/JS/HTML/Text) are available. More can be added easily.
2. Syntax cache size and memory usage for syntax highlighting is massively reduced.
3. More fine gained syntax highlighting. `{{ var }}` interpolation clears `string` scope in quoted strings, while does not in others, which is common practice in most other template syntaxes and normal interpolation constructs. (See: Liquid, Slim, Jinja, PHP, ...).
4. Works around a bug in ST4180
5. Will prevent context sanity limit being hit in up-coming releases, which will otherwise be triggered due to JavaScript supporting syntax highlighted tagged template strings.

_Note: In case this package / repository is no longer maintained or used, feel free to transfer ownership to https://github.com/SublimeText organization, so community can continue maintainance. Various syntax definition packages already found a new home there. We would than take action on updating package control channel, etc._

### CODE REVIEW

**Comment by cedeber** [comment]
Sorry I didn't see the pull request earlier. To be honest I am not a regular user of Sublime Text anymore.
Are you done with your changes? So that I can merge.
I can add you as maintainer if you need?

**Comment by deathaxe** [comment]
Yes, ready to merge.

Note, this release requires quite recent ST4152 release. A new tag (e.g. 4152-1.2.3) would be required for the channel to add a rule to restrict it. Otherwise users with older builds will see errors.

**Comment by cedeber** [comment]
TBH I completely forgot how to upgrade on packagecontrol.io.
I've seen your note as well, I can transfer the repo.

**Comment by deathaxe** [comment]
You are welcome to transfer it to me and I can do the rest, moving it to SublimeText org and update the channel data.

**Comment by cedeber** [comment]
You may need to delete or rename your sublime-mustache repo. The transfer fails because of that.

**Comment by deathaxe** [comment]
Done.

**Comment by cedeber** [comment]
Did you receive the transfer message? It is still pending in the settings for me.

**Comment by deathaxe** [comment]
Haven't realized it, no. Maybe it timed out before I saw it.

**Comment by cedeber** [comment]
I've aborted the previous transfer and did a new one.

**Pull request merged**
